name: Deploy Demo Page

on:
  push:
    branches:
      - main
    paths:
      - 'demo/**'
      - '.github/workflows/deploy-demo.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd demo
          npm install -g serve

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo
          publish_branch: gh-pages
          commit_message: "Deploy demo page"
          force_orphan: true 